### ISSUE TITLE
NuGet package 1.3.1.0 still contains the 1.2.2.0 assembly

### ISSUE THREAD

**Issue by thomaslevesque** [peteraritchie/LongPath#16]
Looks like you packaged the wrong assembly...
It happens to me all the time: I test the Debug configuration, and forget to rebuild the Release configuration before I package ;)

**Comment by thomaslevesque** [comment]
Actually, AssemblyInfo.cs still contains "1.2.2.0", so even if the package contained the right assembly, the version would be wrong. But still, I'm pretty sure this is the wrong assembly, because when I decompile it, the code is clearly different from the source.

**Comment by peteraritchie** [comment]
arg :\.  You are correct.  Thanks for point that out! (you're the first).  I didn't commit the 1.3.1.0 changes either (which where just version # changes).  I've created a 1.3.2 release, pushed the changes, confirmed the nupkg and published a  new Nuget package.  Thanks

**Comment by thomaslevesque** [comment]
Great, thanks for the fix!

**Comment by thomaslevesque** [comment]
BTW, in the repo the AssemblyInfo still says 1.3.1, not 1.3.2. Did you forget to push?

**Comment by peteraritchie** [comment]
yes I did forget.  Fixed now :)
