### ISSUE TITLE
DirectoryInfo.FullName is missing

### ISSUE THREAD

**Issue by am11** [peteraritchie/LongPath#17]
While [enumerating the directory](https://github.com/madskristensen/WebEssentials2013/blob/e100d71b2c9b6048aa4c41d5e84151b0616039af/EditorExtensions/PreBuildTask.cs#L311), I came to realise that [`DirectoryInfo.FullName`](https://msdn.microsoft.com/en-us/library/system.io.filesysteminfo.fullname.aspx) is missing and the closest one `DirectoryInfo.FullPath` (inherited) is marked as `protected`.

Please add `.FullName` property to the API.

**Comment by peteraritchie** [comment]
FullName is in the base FileSystemInfo and is public virtual, that's not working?

**Comment by am11** [comment]
Ops its my silly mistake. I just checked in object browser and you are right, its in base class! We are actually using `Pri.LongPath` via reflection in `MSBuildTask`, uncommenting that line is chocking the compilation. 

Sorry for the confusion. :)
