### ISSUE TITLE
Bug in  Pri.LongPath.Path.GetDirectoryName when filename contains dot + whitespace

### ISSUE THREAD

**Issue by ngjermundshaug** [peteraritchie/LongPath#32]
There is a bug in Pri.LongPath.Path.GetDirectoryName when the filename contains '. ' (dot and then whitespace).

    System.IO.Path.GetDirectoryName("C:\\myfolder\\Con. approval.pdf")    // ==> C:\myfolder (correct)
    Pri.LongPath.Path.GetDirectoryName("C:\\myfolder\\Con. approval.pdf") // ==> \\. (not correct)

Seems to be a win32 bug:

    NativeMethods.GetFullPathName("C:\\myfolder\\Con. approval.pdf", (uint)buffer.Capacity, buffer, IntPtr.Zero) ==> buffer is set to \\.\Con - which is not correct

I have reported this here: https://msdn.microsoft.com/en-us/library/windows/desktop/aa364963(v=vs.85).aspx

**Comment by peteraritchie** [comment]
If it's a windows bug, there may not be much that can be done.

**Comment by thomaslevesque** [comment]
It's not because of the whitespace, it's because of the "con". "con" is a reserved filename, and a filename cannot include it as a whole word (of course something like "context" or "defcon" is fine).

**Comment by ngjermundshaug** [comment]
Awesome! Thanks for clearing this up Thomas!
