### ISSUE TITLE
DirectoryInfo.EnumerateFiles(); is missing

### ISSUE THREAD

**Issue by FuchsiaSoft** [peteraritchie/LongPath#33]
In v2.0.0-beta the ``` DirectoryInfo.EnumerateFiles() ``` method is no longer available from an instance of ``` DirectoryInfo ``` class for projects that are .Net 4.5+

This worked fine in v1.3.2 and emulated the behaviour of ``` System.IO ``` returning ``` IEnumerable<FileInfo> ```

From my testing (using VS 2015 and the nuget prelease) it still works fine in .Net 4.0

**Comment by peteraritchie** [comment]
Hmm, that's interesting.  That wasn't done on purpose.  I'll have a look.  Thanks.

**Comment by peteraritchie** [comment]
@FuchsiaSoft when you say 4.5+, are you talking about a project in VS 2015 or 4.5.1 and 4.6?

**Comment by FuchsiaSoft** [comment]
@peteraritchie I tried it with 4.5 and 4.5.2, both had the issue for me

**Comment by FuchsiaSoft** [comment]
Also it was in vs 2015

**Comment by peteraritchie** [comment]
ok, not seeing it in 2013.  I'll have to try with 2015 later.

**Comment by FuchsiaSoft** [comment]
I've tried it in 2013 and have the same issue in 4.5 projects but only from the nuget package.

On downloading the source solution I can add a new project and reference Pri.LongPath internally and it works fine.

I can create a sample repository and post a link if it helps?

**Comment by peteraritchie** [comment]
Even more interesting. Let me have more of a look and I'll let you know if I need anything else. Thanks

**Comment by peteraritchie** [comment]
@FuchsiaSoft I tried with a 2013 project for 4.5 and 4.5.1 and I'm not seeing any problems.  If you have an 2013 example of the problem, could you please attach a zip to the thread?

**Comment by FuchsiaSoft** [comment]
Will do... it'll be about 12 hours from now though with time diff

**Comment by FuchsiaSoft** [comment]
Sorry for the delay I got caught up with something else.

GitHub won't allow me to attach a zip to this thread, so I've put it into a sample repo here:
https://github.com/FuchsiaSoft/LongPathTest

Direct link to the repo as a zip here:
https://github.com/FuchsiaSoft/LongPathTest/archive/master.zip

It's a console application made in Express 2013 targeting .Net 4.5

Pri.LongPath 2.0 was added from nuget as prerelease to it

**Comment by peteraritchie** [comment]
Cool, thanks @FuchsiaSoft

**Comment by peteraritchie** [comment]
Fixed by commit 785f14b2272a43e3036a8563438c683d00ea00b4

**Comment by peteraritchie** [comment]
It just happened to be a compiler constant not being defined in the Release project.  I'm surprised no one noticed it until now :).  Thanks.

**Comment by FuchsiaSoft** [comment]
Thank you very much for your time... I'd worked around it with GetFiles for the project I'm currently working on but glad I don't have to change any others now it's fixed.

Thanks again :smiley:
