### ISSUE TITLE
Directory.EnumerateFiles is missing overloads in .NET 4

### ISSUE THREAD

**Issue by nkraft** [peteraritchie/LongPath#35]
Directory.EnumerateFiles(String, String) and Directory.EnumerateFiles(String, String, SearchOption) are excluded for .NET 4 but present for .NET 4.5. In the original System.IO API these overloads are available in .NET 4 (see https://msdn.microsoft.com/en-us/library/system.io.directory.enumeratefiles(v=vs.100).aspx)

**Comment by FuchsiaSoft** [comment]
Hi, I don't work on this repo but use it a lot... I had the same issue and resolution is here:

https://github.com/peteraritchie/LongPath/issues/33

**Comment by peteraritchie** [comment]
yes, fixed by #33

**Comment by nkraft** [comment]
Maybe I'm missing something here, but #33 and the associated fixing commit deal with missing functionality in .NET 4.5 projects. This issue relates to missing functionality in .NET 4 projects.

**Comment by peteraritchie** [comment]
@nkraft Are you using one of the latest versions (e.g. 2.0.16)?  I just tried creating a new console application in VS 2015 with target framework of `.NET Framework 4.0` and added the package Pri.LongPath.  no problem with `Directory.EnumerateFiles(string)` or ``

**Comment by peteraritchie** [comment]
Good catch @nkraft. I'm not sure how those got marked as 4.0-only. Looking into a fix

**Comment by peteraritchie** [comment]
fixed by 080aebe
