### ISSUE TITLE
Path.GetFileName throws if path is null

### ISSUE THREAD

**Issue by canton7** [peteraritchie/LongPath#38]
`System.IO.Path.GetFileName` returns `null` if the input is `null`. `Pri.LongPath.Path.GetFileName` used to do the same (since it simply delegated to `System.IO.Path.GetFileName`).

However it no longer does so, since it calls `Path.NormalizeLongPath` which throws if its input is null.

**Comment by peteraritchie** [comment]
closed by 26791699cd3373e814559dc13680df5bc5d17a75

**Comment by canton7** [comment]
:+1: thanks
