### ISSUE TITLE
File Security not working

### ISSUE THREAD

**Issue by nathansantanna** [peteraritchie/LongPath#40]
Im trying to set acl programatically, but "File.SetAccessControl(string path, FileSecurity FileSecurity)"didn't work, "File.GetAccessControl(string path)"  worked fine!

;

**Comment by nathansantanna** [comment]
Sorry, i think i was using an old version, o downloaded the repository, and now is working fine

**Comment by peteraritchie** [comment]
@nathansantanna I believe the latest changes (updated in NuGet) fixes your issue.  Please let me know if it did or not.  Thanks

**Comment by nathansantanna** [comment]
But now, i'm having some problems on  
Directory.SetAccessControl(string Path, DirectorySecurity directorySecurity )
File.SetAccessControl(string Path, FileSecurity fileSecurity )

doesn't adds the rule on my folder or file, with System.IO works fine.

Here's how i'm using.
public void RemoveFileSecurity(FileSystemAccessRule rule)
{
            FileSecurity fileSecurity = File.GetAccessControl(Path);
            fileSecurity.RemoveAccessRule(rule);
            System.IO.File.SetAccessControl(Path, fileSecurity);
}

thanks in advance!
