### ISSUE TITLE
Number of EntryPointNotFound exceptions on mono/linux

### ISSUE THREAD

**Issue by spike0xff** [peteraritchie/LongPath#74]
Pri.LongPath 2.0.45

GetFullPathName <= Path.NormalizeLongPath <= File.Copy

CreateFile <= File.GetFileHandle <= File.Open <= File.CreateStreamWriter <= File.WriteAllText(path, contents, encoding)

FileInfo.Refresh (I call it directly)

I would like to submit PRs for these but wanted to document them before I started forgetting what I'd run into...

**Comment by peteraritchie** [comment]
Fixed by #85
