### ISSUE TITLE
Infinite sequence of elements when traversing the directory name consisting of single space

### ISSUE THREAD

**Issue by ForNeVeR** [peteraritchie/LongPath#80]
Create the directory `"C:\Temp\ \"` (the last directory name consists of single space and nothing else). Now call `Directory.EnumerateFileSystemEntries(@"C:\Temp\ \", "*.*", SearchOption.AllDirectories)`.

The method from the LongPath package will return an infinite sequence of elements for this directory; the method from `System.IO` namespace will not.

**Comment by peteraritchie** [comment]
I can't reproduce with the latest version.  I get an empty sequence with LongPath.  Oddly, System.IO returns one element with a non-existant file "c:\temp\ \ ". 🤷‍♂

**Comment by ForNeVeR** [comment]
Okay, I'll try to reproduce this in my spare time and close if it has been fixed. Thanks for info.

Also, I can confirm that `System.IO` is very broken with these outworldish paths.

**Comment by ForNeVeR** [comment]
I can confirm that this issue couldn't be reproduced in Pri.LongPath version 2.0.53. Thanks for your work!
