### ISSUE TITLE
Error: Trying to create a parent directory, which exists but the current user has no permissions.

### ISSUE THREAD

**Issue by ntellos13** [peteraritchie/LongPath#94]
Given the already existing path `D:/git/projects/repo_name/source/project_name/uploads/` with the following permissions:

- D: ~> Full control to `windows_user` & `administrator_group`
- git ~> Full control to `windows_user` & `administrator_group`
- projects ~> Full control to `windows_user` & `administrator_group`
- repo_name ~> Full control to `windows_user` & `administrator_group`
- source ~> Full control to `windows_user` & `administrator_group`
- project_name ~> Full control to `IIS_POOL_USER`, `windows_user` & `administrator_group`
- uploads ~> Full control to `IIS_POOL_USER`, `windows_user` & `administrator_group`

and executing the `Pri.LongPath.Directory.CreateDirectory("D:\git\projects\repo_name\Source\project_name\Uploads\folder_to_create\");` in an app hosted in IIS, running as the `IIS_POOL_USER` the `pathComponents` list contains folders that do exist but the `IIS_POOL_USER` has no permissions.
![image](https://user-images.githubusercontent.com/1238838/207669925-8b2c8ffa-8e65-413a-aed3-a0c2cade7d66.png)
![image](https://user-images.githubusercontent.com/1238838/207671383-6c22bae8-3516-4390-8d35-c252fb225e1c.png)

In the following code:
https://github.com/peteraritchie/LongPath/blob/6133dc9ca935127e1663fef27a52717e4174db3d/Pri.LongPath/Directory.cs#L840-L867

I propose that lines 847 & 848 should be altered like this:
```

					if (Exists(subPath))
					{
						break; // If a subfolder exists then there's no need to check for parent folders
					}
					else
					{
						pathComponents.Add(Path.NormalizeLongPath(subPath));
					}

```

**Comment by peteraritchie** [comment]
Good find, and thanks for the included PR!
